#! /bin/sh

WEBSPACE=/webspace/projects/twilight
CVS=/usr/bin/cvs
CVSROOT=/cvs/cvsroot/twilight

set -e

cd $WEBSPACE
echo "Pulsing the website..."

# And THIS is a hack...
$CVS -q -z3 -d$CVSROOT update -dACP &

