
#include <stdio.h>
#include <string.h>
#ifdef WIN32
#define snprintf _snprintf
#endif

#ifndef PATH_MAX
#define PATH_MAX 1024
#endif

static char *nibbletohex = "0123456789ABCDEF";

int getfilename(int index, char **argv, char *infilename, char *embedfilename, int *autostrings, int *strings, int *hex, int warn)
{
	int j;
	int endofoptions = 0;
	const char *name = argv[index];
	const char *base = "";
	*strings = 0, *hex = 0, *autostrings = 1;
	for (j = 1;j <= index;j++)
	{
		if (!strcmp(argv[j], "--"))
		{
			endofoptions = 1;
			break;
		}
		if (argv[j][0] != '-')
			continue;
		if (!strcmp(argv[j], "-autostrings"))
		{
			*autostrings = 1;
			*strings = 0;
		}
		else if (!strcmp(argv[j], "-strings"))
		{
			*autostrings = 0;
			*strings = 1;
		}
		else if (!strcmp(argv[j], "-array"))
		{
			*autostrings = 0;
			*strings = 0;
		}
		else if (!strcmp(argv[j], "-hex"))
			*hex = 1;
		else if (!strcmp(argv[j], "-dec"))
			*hex = 0;
		else if (!strncmp(argv[j], "-base=", 6))
			base = strchr (argv[j], '=') + 1;
		else if (!strncmp(argv[j], "-strippath=", 11))
		{
			const char *strippath = strchr(argv[j], '=') + 1;
			if (!strncmp(argv[index], strippath, strlen(strippath)))
				name = argv[index] + strlen(strippath);
		}
		else if (j == index)
		{
			if (warn)
				fprintf(stderr, "WARNING: unknown option %s\n", argv[j]);
		}
	}
	if (!endofoptions && argv[index][0] == '-')
		return 0; // not a filename
	// store the real input filename
	snprintf(infilename, PATH_MAX, "%s", argv[index]);
	// append base to the (possibly stripped) path for the embed filename
	snprintf(embedfilename, PATH_MAX, "%s%s", base, name);
	return 1; // decoded a filename
}

int main(int argc, char **argv)
{
	int i, j, c, w, skipstart, filenum, filesize, strings = 0, hex = 0, autostrings = 1;
	FILE *infile;
	static unsigned char readbuf[1048576];
	static char writebuf[sizeof(readbuf) * 6 + 32];
	char	*base = NULL, infilename[PATH_MAX], embedfilename[PATH_MAX];
	if (argc >= 2)
	{
		printf("/*this file generated by %s*/\n\ntypedef struct embeddedfile_s\n{\n\tchar *name;\n\tunsigned char *data;\n\tint datasize;\n}\nembeddedfile_t;\n\n", argv[0]);
		filenum = 0;
		for (i = 1;i < argc;i++)
		{
			if (getfilename(i, argv, infilename, embedfilename, &autostrings, &strings, &hex, 0))
			{
				if (!(infile = fopen(infilename, "rb")))
					continue;
				fseek(infile, 0, SEEK_END);
				filesize = ftell(infile);
				fseek(infile, 0, SEEK_SET);
				if (autostrings)
				{
					// automatically detect binary data and decide type based on it
					for(;;)
					{
						c = fread(readbuf, 1, sizeof(readbuf), infile);
						if (c < 1)
							break;
						for (j = 0;j < c;j++)
							if (readbuf[j] != '\t' && readbuf[j] != '\r' && readbuf[j] != '\n' && (readbuf[j] < ' ' || readbuf[j] >= 0x7F))
								break;
						if (j == c)
							strings = 1;
						else
							strings = 0;
					}
					fseek(infile, 0, SEEK_SET);
				}
				printf("/*file \"%s\"*/\n", embedfilename);
				if (strings/* && filesize < 8192*/)
				{
					printf("char embeddedfile_data%i[%i] =", filenum, filesize);
					filenum++;
					for(;;)
					{
						c = fread(readbuf, 1, sizeof(readbuf), infile);
						if (c < 1)
							break;
						w = 0;
						writebuf[w++] = '\n';
						writebuf[w++] = '"';
						for (j = 0;j < c;j++)
						{
							if (readbuf[j] == '?')
							{
								writebuf[w++] = '\\';
								writebuf[w++] = '?';
							}
							else if (readbuf[j] == '\\')
							{
								writebuf[w++] = '\\';
								writebuf[w++] = '\\';
							}
							else if (readbuf[j] == '\t' || ((readbuf[j] >= ' ' && readbuf[j] <= 0x7e) && readbuf[j] != '"' && readbuf[j] != '\\'))
								writebuf[w++] = readbuf[j];
							else
							{
								writebuf[w++] = '\\';
								     if (readbuf[j] == '\n')
								{
									writebuf[w++] = 'n';
									writebuf[w++] = '"';
									writebuf[w++] = '\n';
									writebuf[w++] = '"';
								}
								else if (readbuf[j] == '\r')
									writebuf[w++] = 'r';
								else if (readbuf[j] == '\t')
									writebuf[w++] = 't';
								else
								{
									if (readbuf[j] >= 0100 || (j < c - 1 && readbuf[j + 1] >= '0' && readbuf[j + 1] <= '9'))
									{
										writebuf[w++] = ((readbuf[j] >> 6) & 3) + '0';
										writebuf[w++] = ((readbuf[j] >> 3) & 7) + '0';
										writebuf[w++] = ((readbuf[j] >> 0) & 7) + '0';
									}
									else if (readbuf[j] >= 010)
									{
										writebuf[w++] = ((readbuf[j] >> 3) & 7) + '0';
										writebuf[w++] = ((readbuf[j] >> 0) & 7) + '0';
									}
									else
										writebuf[w++] = ((readbuf[j] >> 0) & 7) + '0';
								}
							}
						}
						writebuf[w++] = '"';
						fwrite(writebuf, 1, w, stdout);
					}
					printf(";\n\n");
				}
				else
				{
					skipstart = 1;
					printf("unsigned char embeddedfile_data%i[%i] =\n{", filenum, filesize);
					filenum++;
					for(;;)
					{
						c = fread(readbuf, 1, sizeof(readbuf), infile);
						if (c < 1)
							break;
						w = 0;
						if (skipstart)
							skipstart = 0;
						else
							writebuf[w++] = ',';
						writebuf[w++] = '\n';
						//writebuf[w++] = '\t';
						for (j = 0;j < c;j++)
						{
							if (j > 0)
							{
								writebuf[w++] = ',';
								//writebuf[w++] = ' ';
							}
							if (hex)
							{
								writebuf[w++] = '0';
								writebuf[w++] = 'x';
								writebuf[w++] = nibbletohex[(readbuf[j] >> 4) & 15];
								writebuf[w++] = nibbletohex[readbuf[j] & 15];
							}
							else
							{
								if (readbuf[j] >= 100)
								{
									writebuf[w++] = '0' + ((readbuf[j] / 100));
									writebuf[w++] = '0' + ((readbuf[j] / 10) % 10);
									writebuf[w++] = '0' + ((readbuf[j]) % 10);
								}
								else if (readbuf[j] >= 10)
								{
									writebuf[w++] = '0' + (readbuf[j] / 10);
									writebuf[w++] = '0' + ((readbuf[j]) % 10);
								}
								else
									writebuf[w++] = '0' + readbuf[j];
							}
						}
						fwrite(writebuf, 1, w, stdout);
					}
					printf("\n};\n\n");
				}
				fclose(infile);
			}
		}
		printf("embeddedfile_t embeddedfile[%i] =\n{\n", filenum + 1);
		filenum = 0;
		base = NULL;
		for (i = 1;i < argc;i++)
		{
			if (getfilename(i, argv, infilename, embedfilename, &autostrings, &strings, &hex, 1))
			{
				if ((infile = fopen(infilename, "rb")))
				{
					fseek(infile, 0, SEEK_END);
					filesize = ftell(infile);
					printf("\t{\"%s\", embeddedfile_data%i, %i},\n", embedfilename, filenum, filesize);
					filenum++;
					fclose(infile);
				}
				else
				{
					printf("/*file \"%s\" not found*/\n", embedfilename);
					fprintf(stderr, "WARNING: file \"%s\" not found\n", infilename);
				}
			}
		}
		printf("\t{0, 0, 0}\n};\n");
		return 0;
	}

	fprintf(stderr,
"usage: %s [options] inputfiles\nOptions:\n"
"-autostrings      output strings for pure ASCII-7 files, arrays for binary (default)\n"
"-strings          always output strings with escape codes for non-ASCII characters\n"
"-array            always output files as arrays of bytes\n"
"-hex              when outputting array data, use hexidecimal bytes\n"
"-dec              when outputting array data, use decimal bytes (default)\n"
"-base=path/       prepend this path to filenames in the output\n"
"-strippath=path/  remove this prefix from any filename starting with it\n"
"--                do not interpret parameters past this point as options\n"
		, argv[0]);
	return 1;
}

