
#include <stdio.h>

static char *nibbletohex = "0123456789ABCDEF";

int main(int argc, char **argv)
{
	int i, j, c, w, skipstart, filenum, filesize;
	FILE *infile;
	unsigned char readbuf[16];
	char writebuf[sizeof(readbuf) * 6 + 32];
	if (argc >= 2)
	{
		printf("/*this file generated by %s*/\n\ntypedef struct embeddedfile_s\n{\n\tchar *name;\n\tunsigned char *data;\n\tint datasize;\n}\nembeddedfile_t;\n\n", argv[0]);
		filenum = 0;
		for (i = 1;i < argc;i++)
		{
			infile = fopen(argv[i], "rb");
			if (infile)
			{
				fseek(infile, 0, SEEK_END);
				filesize = ftell(infile);
				fseek(infile, 0, SEEK_SET);
				printf("/*file \"%s\"*/\nunsigned char embeddedfile_data%i[%i] =\n{", argv[i], filenum, filesize);
				filenum++;
				skipstart = 1;
				for(;;)
				{
					c = fread(readbuf, 1, sizeof(readbuf), infile);
					if (c < 1)
						break;
					w = 0;
					if (skipstart)
						skipstart = 0;
					else
						writebuf[w++] = ',';
					writebuf[w++] = '\n';
					writebuf[w++] = '\t';
					for (j = 0;j < c;j++)
					{
						if (j > 0)
						{
							writebuf[w++] = ',';
							writebuf[w++] = ' ';
						}
						writebuf[w++] = '0';
						writebuf[w++] = 'x';
						writebuf[w++] = nibbletohex[(readbuf[j] >> 4) & 15];
						writebuf[w++] = nibbletohex[readbuf[j] & 15];
					}
					fwrite(writebuf, 1, w, stdout);
				}
				printf("\n};\n\n");
				fclose(infile);
			}
			else
			{
				printf("/*file \"%s\" not found*/\n", argv[i]);
				fprintf(stderr, "file \"%s\" not found\n", argv[i]);
			}
		}
		printf("embeddedfile_t embeddedfile[] =\n{\n");
		filenum = 0;
		for (i = 1;i < argc;i++)
		{
			infile = fopen(argv[i], "rb");
			if (infile)
			{
				fseek(infile, 0, SEEK_END);
				filesize = ftell(infile);
				printf("\t{\"%s\", embeddedfile_data%i, %i},\n", argv[i], filenum, filesize);
				filenum++;
				fclose(infile);
			}
			else
				printf("/*file \"%s\" not found*/\n", argv[i]);
		}
		printf("\t{0, 0, 0}\n};\n");
		return 0;
	}

	fprintf(stderr, "usage: %s inputfiles\n", argv[0]);
	return 1;
}

